### ISSUE TITLE
ERROR: No matching distribution found for tensorflow-cpu

### ISSUE THREAD

**Issue by HenryZhuhongyin** [nowickam/facial-animation#4]
any suggestion for me how to find the right tensorflow-cpu version?
I got an error when run: pip install -r requirements.txt

Error info
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu

this is my enviroment:
MacBook Pro（16，2021）Apple M1 Pro, macos monterey 12.5.1

**Comment by nowickam** [comment]
Unfortunately, I am not aware of how to deal with the M1 architecture. [Apple developers](https://developer.apple.com/metal/tensorflow-plugin/) suggest:
`conda install -c apple tensorflow-deps`
`python -m pip install tensorflow-macos`
`python -m pip install tensorflow-metal`
