### ISSUE TITLE
How to animate character after getting the prediction result i.e. phoneme result and viseme result?

### ISSUE THREAD

**Issue by ujjawalcse** [nowickam/facial-animation#5]
Hey @nowickam ,
I couldn't get how you are using the result to animate the character.
Suppose we have a character having 61 blendshapes (here the number of phonemes), what value 
should be assigned to these blendshapes?

Please clarify if i'm getting the point.
Thanks.

**Comment by nowickam** [comment]
There are in fact 8 blend shapes for the model and their different combinations (with different, preassigned values determining the expressivity of the shape) constitute 11 visemes (facial representations of a sound), which are assigned to groups of phones. The phones are classified real-time, and the combinations of values are interpolated for smooth transitions between visemes.
Refer to [Audio Driven Facial Animation Thesis](https://github.com/nowickam/facial-animation/files/9758888/Bachelor_Thesis_Nowicka_Zawadka.1.pdf) to learn in detail about the implementation.

**Comment by ujjawalcse** [comment]
Thanks @nowickam .
